# Generated by Django 4.2 on 2023-12-28 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite',
            name='user_class',
        ),
        migrations.RemoveField(
            model_name='mysite',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mysite',
            name='user_name',
        ),
        migrations.AddField(
            model_name='mysite',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='mysite',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='mysite',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
